// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("API.Entities.AccountInfo", b =>
                {
                    b.Property<int>("custID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("accountName")
                        .HasColumnType("TEXT");

                    b.Property<int>("accountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("availableBal")
                        .HasColumnType("INTEGER");

                    b.HasKey("custID");

                    b.ToTable("AccountInfos");
                });

            modelBuilder.Entity("API.Entities.LoginCredential", b =>
                {
                    b.Property<int>("custID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("custID");

                    b.ToTable("LoginCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
