# Generated by Django 3.1.2 on 2020-12-11 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_accountdetails_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionamounts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 6, 26, 37, 774617)),
        ),
    ]
