# Generated by Django 3.1.2 on 2020-12-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_transactionamounts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionamounts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
